apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  #namespace: staging
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      #nodeSelector:
      #  cloud.google.com/gke-nodepool: pool-e2-high-2
      containers:
        - name: redis
          image: 6.2.1-alpine # redis 6 alpine
          imagePullPolicy: Always
          # --io-threads number based on CPU core, leaving at least one spare core
          # we suggest enabling it only in machines that have at least 4 or more cores
          # volatile-lfu better performance hits ratio
          args: ["--appendonly", "no","--maxmemory-policy", "volatile-lfu", "--io-threads", "3"]
          ports:
            - containerPort: 6379
              protocol: TCP
              name: redis
          resources:
              limits:
                 cpu: "4" # 4 core
                 memory: "8000Mi"
---
## config for service
apiVersion: v1
kind: Service
metadata:
  name: redis
  #namespace: staging
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
